<?php
/**
 * Created by PhpStorm.
 * PersonalCenter : wangjinzeng
 * Date: 2019/4/1
 * Time: 15:11
 */

namespace app\api\controller\v1;


use app\common\model\User;
use think\Controller;
use think\File;

class BaseController extends Controller
{
    public $input;
    public $user_id;
    public $userinfo = [];
    public $userModel;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->input = input();
        $this->getUserInfo($this->input['type'],$this->input['code']);
    }


    public function getUserInfo($type, $code)
    {
        $this->userModel = new User();
        if ($type == 'wechat') {
            $res = $this->getUserInfoByWechat($code);
            if (!$res) {
                return returnMessage(1, '授权失败');
            }

        } elseif ($type == 'ali') {
            $this->getUserInfoByAli();
            //Todo
        }

        if (isset($this->input['user_id']) and !empty($this->input['user_id'])) {
            $user_info = $this->userModel->getUserInfo($this->input['user_id']);

            $result = $this->userModel->updateInfo($res, $this->input['id']);
        } else {
            $result = $this->userModel->addUserInfo($res);
        }
        if ($result) {
            $this->user_id = $result;
            $this->userinfo = $res;
        }
        echo json_encode(['status' => 1, 'msg' => '登陆失败'], JSON_UNESCAPED_UNICODE);
        die();    }

    /**
     * 获取微信用户信息
     * @param $code
     */
    public function getUserInfoByWechat($code)
    {
        $get_openid_url = "https://api.weixin.qq.com/sns/oauth2/access_token?appid=" . config('appid') . "&secret=" . config('appsecret') . "&code=" . $code . "&grant_type=authorization_code";
        $res = httpGet($get_openid_url);
        $access_token = $res['access_token'];
        $openid = $res['openid'];
        $get_info_url = "https://api.weixin.qq.com/sns/userinfo?access_token=" . $access_token . "&openid=" . $openid . "&lang=zh_CN";
        $result = httpGet($get_info_url);
        pre($result);
        //TODO 调式
    }

    public function getUserInfoByAli()
    {
        //TODO 获取支付宝用户信息
    }

    public function valiadateToken($token,$user_info)
    {
        if (!empty($token)) {
            if ($user_info->token !== $token) {
                echo json_encode(['status' => 2, 'msg' => '检测到您的账号在另一端登录，请重新登录22222'], JSON_UNESCAPED_UNICODE);
                die();
            }
        }
    }


    //单图
    public function upLoad($data, $files)
    {
        foreach ($files as $name => $file) {
            /** @var File $file */
            $info = $file->rule('date')->validate(['size' => config('img_size'), 'ext' => config('img_type')])->move('../public/uploads/Engineer');
            if ($info) {
                $data[$name] = '/uploads/Engineer/' . $info->getSaveName();
            } else {
                return returnMessage('1', $file->getError());
            }
        }
        return $data;
    }


    /**
     * 多图
     * @param $file
     * @return string
     */
    public function move($file)
    {
        if ($file) {
            /** @var File $file */
            $info = $file->validate(['ext' => 'img,png,jpg'])->move("../public/uploads/img/");
            if (!$info) return returnMessage(1, $info->getError());

            $fileName = "/uploads/img/" . $info->getSaveName();
            $fileName = str_replace("\\", "/", $fileName);
            return $fileName;
        } else {
            return '';
        }
    }
}