<?php
/**
 * Created by PhpStorm.
 * PersonalCenter : wangjinzeng
 * Date: 2019/4/1
 * Time: 15:11
 */

namespace app\api\controller\v1;


use think\Controller;
use think\File;
use think\Db;

class BaseController extends Controller
{
    public $input;
    public $user_id; // 用户id
    public $e_id;  // 工程师id
    public $userinfo = [];


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->input = input();
        $this->validata($this->input)->getUserInfo($this->input['phone'])->valiadateToken($this->input['token']);
    }
    /**
     * @param $data
     * @return $this
     */
    public function validata($data)
    {
        if (empty($data['token']) || empty($data['phone'])) {
            echo json_encode(['status' => 1, 'msg' => 'token不能为空 或 手机号不能为空']);
            die();
        }
        return $this;
    }

    public function getUserInfo($phone)
    {
        try {
            $user_info = Db::table('ln_user_info')->where(['phone' => $phone])->find();
            if (!$user_info) {
                echo json_encode(['status' => '8', 'msg' => '无此用户']);
                die();
            }
            $this->userinfo = $user_info;
            return $this;
        } catch (\Exception $e) {
            echo json_encode(['status' => '12', 'msg' => '服务器繁忙']);
            die();
        }

    }

    public function valiadateToken($token)
    {
        if (!empty($token)) {
            if ($this->userinfo['token'] !== $token) {
                echo json_encode(['status' => 2, 'msg' => '检测到您的账号在另一端登录，请重新登录22222'], JSON_UNESCAPED_UNICODE);
                die();
            }
        }
    }

    //单图
    public function upLoad($data, $files)
    {
        foreach ($files as $name => $file) {
            /** @var File $file */
            $info = $file->rule('date')->validate(['size' => config('img_size'), 'ext' => config('img_type')])->move('../public/uploads/Engineer');
            if ($info) {
                $data[$name] = '/uploads/Engineer/' . $info->getSaveName();
            } else {
                return returnMessage('1', $file->getError());
            }
        }
        return $data;
    }



    /**
     * 多图
     * @param $file
     * @return string
     */
    public function move($file)
    {
        if ($file) {
            /** @var File $file */
            $info = $file->validate(['ext' => 'img,png,jpg'])->move( "../public/uploads/img/");
            if (!$info) return returnMessage(1, $info->getError());

            $fileName = "/uploads/img/" . $info->getSaveName();
            $fileName = str_replace("\\","/",$fileName);
            return $fileName;
        } else {
            return '';
        }
    }

}